const router = require('express').Router()
const dataMemberRouter = require('./data-member.router')
const dataNomorPolisiRouter = require('./data-nomor-polisi.router')
const dataVoucherRouter = require('./data-voucher.router')
const kendaraanRouter = require('./kendaraan.router')
const levelPenggunaRouter = require('./level-pengguna.router')
const perusahaanRouter = require('./perusahaan.router')
const posRouter = require('./pos.router')
const produkMemberRouter = require('./produk-member.router')
const produkVoucherRouter = require('./produk-voucher.router')
const shiftRouter = require('./shift.router')
const dataNomorPolisiV2Router = require('./data-nomor-polisi-v2.router')

router.use('/data-nomor-polisi-v2', dataNomorPolisiV2Router)
router.use('/data-member', dataMemberRouter)
router.use('/data-nomor-polisi', dataNomorPolisiRouter)
router.use('/data-voucher', dataVoucherRouter)
router.use('/kendaraan', kendaraanRouter)
router.use('/level-pengguna', levelPenggunaRouter)
router.use('/perusahaan', perusahaanRouter)
router.use('/pos', posRouter)
router.use('/produk-member', produkMemberRouter)
router.use('/produk-voucher', produkVoucherRouter)
router.use('/shift', shiftRouter)

module.exports = router
