// src/controllers/setting/parameterDefaultsManless.js

module.exports = [
  { nama: 'Foto Pintu Masuk', nilai: '-', keterangan: '-' },
  { nama: 'Foto Pintu Keluar', nilai: '-', keterangan: '-' },
  { nama: 'Default Nomor Polisi', nilai: '-', keterangan: '-' },
  { nama: 'Waktu Minimal Durasi Parkir', nilai: '-', keterangan: '-' },
  { nama: 'Nama Komputer Server', nilai: '-', keterangan: '-' },
  { nama: 'Autocomplete Nopol Member', nilai: '-', keterangan: '-' },
  { nama: 'Bayar Member Ketika Keluar', nilai: '-', keterangan: '-' },
  { nama: 'Reset Tarif Setelah 1 x 24 Jam', nilai: '-', keterangan: '-' },
  { nama: 'Aktif Tarif Maksimal', nilai: '-', keterangan: '-' },
  { nama: 'Bayar Member Secara Berjenjang', nilai: '-', keterangan: '-' },
  { nama: 'Konfirmasi Denda Tiket Hilang', nilai: '-', keterangan: '-' },
  { nama: 'Ijinkan PK Input Member', nilai: '-', keterangan: '-' },
  { nama: 'Print bill secara otomatis', nilai: '-', keterangan: '-' },
  { nama: 'Aktif Log Transaksi PM', nilai: '-', keterangan: '-' },
  { nama: 'Aktif Log Transaksi PK', nilai: '-', keterangan: '-' },
  { nama: 'Metode Cepat Input Member', nilai: '-', keterangan: '-' },
  { nama: 'Fleksibel Masa Aktif Member', nilai: '-', keterangan: '-' },
  { nama: 'Jml Hari Perpanjangan Member', nilai: '-', keterangan: '-' },
  { nama: 'Tiket : Header Tiket Masuk', nilai: '-', keterangan: '-' },
  { nama: 'Tiket : Tampil Nama Pengelola Parkir', nilai: '-', keterangan: '-' },
  { nama: 'Tiket : Footer Baris 1 Tiket Masuk', nilai: '-', keterangan: '-' },
  { nama: 'Tiket : Footer Baris 2 Tiket Masuk', nilai: '-', keterangan: '-' },
  { nama: 'Tiket : Footer Baris 3 Tiket Masuk', nilai: '-', keterangan: '-' },
  { nama: 'Tiket : Header Bill', nilai: '-', keterangan: '-' },
  { nama: 'Tiket : Footer Baris 1 Bill', nilai: '-', keterangan: '-' },
  { nama: 'Tiket : Footer Baris 2 Bill', nilai: '-', keterangan: '-' },
  { nama: 'Izinkan Member Tap In Jika Data In Sebelumnya Belum Keluar', nilai: '-', keterangan: '-' },
  { nama: 'Jenis Kartu Member', nilai: '-', keterangan: '-' },
  { nama: 'Jika Bukan Member Izinkan Masuk', nilai: '-', keterangan: '-' },
  { nama: 'Bypass Transaksi di Basement', nilai: '-', keterangan: '-' },
  { nama: 'Tentukan PM Sesuai Dengan Kartu Aksesnya', nilai: '-', keterangan: '-' },
]
