module.exports = [
  { nama_printer: 'EPSON TM-T82 Receipt' },
  { nama_printer: 'EPSON LX-310 POS' },
  { nama_printer: 'Canon LBP2900' },
  { nama_printer: 'HP LaserJet Pro M12a' },
  { nama_printer: 'Brother HL-1201' },
  { nama_printer: 'Zebra ZD220' },
  { nama_printer: 'EPSON TM-U220' },
  { nama_printer: 'EPSON LQ-2190 ESC/P2' },
  { nama_printer: 'EPSON EcoTank L3110' },
  { nama_printer: 'Canon PIXMA G2020' },
  { nama_printer: 'HP DeskJet Ink Advantage 2336' },
  { nama_printer: 'Brother DCP-T420W' },
  { nama_printer: 'Zebra GK420t' },
  { nama_printer: 'EPSON TM-T88V' },
  { nama_printer: 'Canon imageCLASS MF3010' },
  { nama_printer: 'HP OfficeJet Pro 8020' },
  { nama_printer: 'Brother HL-L2320D' },
  { nama_printer: 'Zebra ZT230 Industrial' },
  { nama_printer: 'EPSON FX-2190II' },
  { nama_printer: 'Canon Selphy CP1300' },
  { nama_printer: 'HP LaserJet MFP M141w' },
  { nama_printer: 'Brother MFC-L2710DW' },
  { nama_printer: 'Zebra ZQ520 Mobile' },
  { nama_printer: 'EPSON TM-T20II' }
]
