module.exports = [
  { nama_interface: 'BGI' },
  { nama_interface: 'USB 2.0' },
  { nama_interface: 'USB 3.0' },
  { nama_interface: 'USB Type-C' },
  { nama_interface: 'Serial RS-232' },
  { nama_interface: 'Parallel Port (LPT)' },
  { nama_interface: 'Ethernet RJ-45' },
  { nama_interface: 'Wi-Fi 802.11b/g/n' },
  { nama_interface: 'Bluetooth 4.0' },
  { nama_interface: 'Bluetooth 5.0' },
  { nama_interface: 'IEEE 1284 Parallel' },
  { nama_interface: 'Infrared (IrDA)' },
  { nama_interface: 'FireWire (IEEE 1394)' },
  { nama_interface: 'NFC (Near Field Communication)' },
  { nama_interface: 'PS/2 Port' },
  { nama_interface: 'Thunderbolt 3' },
  { nama_interface: 'Thunderbolt 4' },
  { nama_interface: 'Wi-Fi Direct' },
  { nama_interface: 'Zigbee' },
  { nama_interface: 'Serial TTL' },
  { nama_interface: 'RJ-11 (Fax Line)' },
  { nama_interface: 'Centronics 36-pin' },
  { nama_interface: 'SCSI' },
  { nama_interface: 'LPT1 Virtual Port' },
  { nama_interface: 'COM1 Virtual Port' },
  { nama_interface: 'CAN Bus' },
  { nama_interface: 'I2C (Inter-Integrated Circuit)' },
  { nama_interface: 'SPI (Serial Peripheral Interface)' },
  { nama_interface: 'GPIO (General Purpose I/O)' },
  { nama_interface: 'PCI Express (PCIe)' },
  { nama_interface: 'Mini USB' },
  { nama_interface: 'Micro USB' },
  { nama_interface: 'eSATA' },
  { nama_interface: 'DisplayPort (for multifunction devices)' },
  { nama_interface: 'HDMI (for all-in-one printers)' },
  { nama_interface: 'Modbus RTU' },
  { nama_interface: 'Modbus TCP/IP' },
  { nama_interface: 'RS-485' },
  { nama_interface: 'RS-422' },
  { nama_interface: 'XLR (industrial signal interface)' }
];
